# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(331, 372)
        MainWindow.setMinimumSize(QtCore.QSize(331, 372))
        MainWindow.setMaximumSize(QtCore.QSize(331, 372))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 91, 16))
        self.label_2.setObjectName("label_2")
        self.score1_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.score1_label.setGeometry(QtCore.QRect(50, 110, 41, 16))
        self.score1_label.setObjectName("score1_label")
        self.score2_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.score2_label.setGeometry(QtCore.QRect(50, 150, 41, 16))
        self.score2_label.setObjectName("score2_label")
        self.score3_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.score3_label.setGeometry(QtCore.QRect(50, 190, 41, 16))
        self.score3_label.setObjectName("score3_label")
        self.score4_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.score4_label.setGeometry(QtCore.QRect(50, 230, 41, 16))
        self.score4_label.setObjectName("score4_label")
        self.name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name.setGeometry(QtCore.QRect(110, 20, 113, 20))
        self.name.setObjectName("name")
        self.attempts = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.attempts.setGeometry(QtCore.QRect(110, 70, 113, 20))
        self.attempts.setObjectName("attempts")
        self.score1_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.score1_line.setGeometry(QtCore.QRect(110, 110, 113, 20))
        self.score1_line.setObjectName("score1_line")
        self.score2_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.score2_line.setGeometry(QtCore.QRect(110, 150, 113, 20))
        self.score2_line.setObjectName("score2_line")
        self.score3_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.score3_line.setGeometry(QtCore.QRect(110, 190, 113, 20))
        self.score3_line.setObjectName("score3_line")
        self.score4_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.score4_line.setGeometry(QtCore.QRect(110, 230, 113, 20))
        self.score4_line.setObjectName("score4_line")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(130, 270, 56, 17))
        self.submit_button.setObjectName("submit_button")
        self.message = QtWidgets.QLabel(parent=self.centralwidget)
        self.message.setGeometry(QtCore.QRect(20, 300, 271, 20))
        self.message.setText("")
        self.message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.message.setObjectName("message")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 331, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grades"))
        self.label.setText(_translate("MainWindow", "Student name"))
        self.label_2.setText(_translate("MainWindow", "No. of attempts"))
        self.score1_label.setText(_translate("MainWindow", "Score 1"))
        self.score2_label.setText(_translate("MainWindow", "Score 2"))
        self.score3_label.setText(_translate("MainWindow", "Score 3"))
        self.score4_label.setText(_translate("MainWindow", "Score 4"))
        self.submit_button.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
